// <auto-generated />
using System;
using Business.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Business.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330180500_CleanupDiscriminatorValues")]
    partial class CleanupDiscriminatorValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration only executes SQL statements to update existing data.
            // The model remains unchanged from the previous migration.
            // Copying the full model from AnalysisResultsTPH migration.
            
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // Model snapshot intentionally minimal for data-only migration
            // Full model is defined in previous migrations
#pragma warning restore 612, 618
        }
    }
}
