// <auto-generated />
using System;
using Business.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Business.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Common.Entities.AlertFlag", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlertFlagType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SensorType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserKey")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("UserKey", "Status");

                    b.ToTable("AlertFlags");
                });

            modelBuilder.Entity("Common.Entities.AnalysisResultContainer", b =>
                {
                    b.Property<string>("KeyField")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("Key");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceAlertKeyField")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasError")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFromCache")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JsonValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserKeyField")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("UserKey");

                    b.HasKey("KeyField");

                    b.HasIndex("DeviceAlertKeyField");

                    b.HasIndex("Discriminator");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserKeyField");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("Common.Entities.DeviceAlertEntity", b =>
                {
                    b.Property<string>("KeyField")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("Key");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceKeyField")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("DeviceKey");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<string>("DeviceUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserKeyField")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("UserKey");

                    b.HasKey("KeyField");

                    b.HasIndex("DeviceKeyField");

                    b.HasIndex("DeviceUid");

                    b.HasIndex("Priority");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserKeyField");

                    b.ToTable("DeviceAlerts", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("DeviceAlertEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Common.Entities.DeviceTokenEntity", b =>
                {
                    b.Property<string>("DeviceUid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserKeyField")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("DeviceUid");

                    b.HasIndex("TokenValue");

                    b.ToTable("DeviceTokens", (string)null);
                });

            modelBuilder.Entity("Common.Entities.KnownPhishingWebsite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Key");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateDeleted");

                    b.HasIndex("Domain");

                    b.HasIndex("Url")
                        .HasDatabaseName("idx_url");

                    b.ToTable("KnownPhishingWebsites", (string)null);
                });

            modelBuilder.Entity("Common.Entities.SafeDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Key");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.ToTable("SafeDomains", (string)null);
                });

            modelBuilder.Entity("Common.Entities.User", b =>
                {
                    b.Property<string>("KeyField")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("Key");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GuardianKey")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Locale")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Timezone")
                        .HasColumnType("int");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KeyField");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Common.Entities.UserAccount", b =>
                {
                    b.Property<string>("KeyField")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("Key");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Is2FactorAuth")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LoginPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LoginUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserKeyField")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("UserKey");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("KeyField");

                    b.HasIndex("UserKeyField");

                    b.HasIndex("UserName");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Common.Entities.UserDevice", b =>
                {
                    b.Property<string>("KeyField")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("Key");

                    b.Property<int>("AggregateVersionField")
                        .HasColumnType("int");

                    b.Property<string>("BiosSerial")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<string>("DeviceUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IMEI")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MAC")
                        .HasColumnType("longtext");

                    b.Property<string>("Make")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<int>("MonitoringStatus")
                        .HasColumnType("int");

                    b.Property<int>("OperatingSystem")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Serial")
                        .HasColumnType("longtext");

                    b.Property<string>("UserKeyField")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("UserKey");

                    b.HasKey("KeyField");

                    b.HasIndex("DeviceUid")
                        .IsUnique();

                    b.ToTable("UserDevices");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserDevice");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Common.Entities.RemoteAccessAlertEntity", b =>
                {
                    b.HasBaseType("Common.Entities.DeviceAlertEntity");

                    b.Property<int>("ConnectionStatus")
                        .HasColumnType("int");

                    b.Property<string>("ConnectionType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConnectionUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ConnectionsCount")
                        .HasColumnType("int");

                    b.Property<bool>("FileTransferActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FileTransfers")
                        .HasColumnType("int");

                    b.Property<int>("RemoteAccessApp")
                        .HasColumnType("int");

                    b.Property<string>("RemoteOS")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RemoteVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RunningProcesses")
                        .HasColumnType("int");

                    b.Property<int>("SessionStatus")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("RemoteAccess");
                });

            modelBuilder.Entity("Common.Entities.TrackUrlAlertEntity", b =>
                {
                    b.HasBaseType("Common.Entities.DeviceAlertEntity");

                    b.Property<int>("TrackerCount")
                        .HasColumnType("int");

                    b.Property<string>("TrackerKeys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UrlAlertEntity_Url");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UrlAlertEntity_UserAgent");

                    b.HasDiscriminator().HasValue("TrackUrl");
                });

            modelBuilder.Entity("Common.Entities.UrlAlertEntity", b =>
                {
                    b.HasBaseType("Common.Entities.DeviceAlertEntity");

                    b.Property<string>("IFrameDomains")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackerKeys")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UrlAlertEntity_TrackerKeys");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Url");
                });

            modelBuilder.Entity("Common.Entities.PersonalComputer", b =>
                {
                    b.HasBaseType("Common.Entities.UserDevice");

                    b.Property<string>("MotherboardSerial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Timezone")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasDiscriminator().HasValue("PC");
                });

            modelBuilder.Entity("Common.Entities.SmartPhone", b =>
                {
                    b.HasBaseType("Common.Entities.UserDevice");

                    b.HasDiscriminator().HasValue("Phone");
                });

            modelBuilder.Entity("Common.Entities.AnalysisResultContainer", b =>
                {
                    b.HasOne("Common.Entities.DeviceAlertEntity", "DeviceAlert")
                        .WithMany()
                        .HasForeignKey("DeviceAlertKeyField");

                    b.HasOne("Common.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserKeyField")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceAlert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.Entities.DeviceAlertEntity", b =>
                {
                    b.HasOne("Common.Entities.UserDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceKeyField")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Common.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserKeyField")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
