// <auto-generated />
// Source: contracts/messaging/v1/envelope.schema.json. Do not edit by hand.
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Common.Generated.Messaging.V1;

public static class MessagingContractV1
{
    public const string SchemaVersion = "1.0";
    public const string EnvelopeSchemaSha256 = "__SCHEMA_SHA256__";
}

public sealed record class MessageEnvelopeV1
{
    [JsonPropertyName("schemaVersion")] public string SchemaVersion { get; init; } = MessagingContractV1.SchemaVersion;
    [JsonPropertyName("messageId")] public Guid MessageId { get; init; }
    [JsonPropertyName("correlationId")] public Guid CorrelationId { get; init; }
    [JsonPropertyName("requestId")] public Guid RequestId { get; init; }
    [JsonPropertyName("messageType")] public string MessageType { get; init; } = string.Empty;
    [JsonPropertyName("sentAt")] public DateTimeOffset SentAt { get; init; }
    [JsonPropertyName("source")] public string Source { get; init; } = string.Empty;
    [JsonPropertyName("context")] public MessageContextV1 Context { get; init; } = new();
    [JsonPropertyName("outcome")] public MessageOutcomeV1? Outcome { get; init; }
    [JsonPropertyName("payload")] public JsonElement Payload { get; init; }
}

public sealed record class MessageContextV1
{
    [JsonPropertyName("deviceId")] public string? DeviceId { get; init; }
    [JsonPropertyName("tabId")] public string? TabId { get; init; }
    [JsonPropertyName("url")] public string Url { get; init; } = string.Empty;
}

public sealed record class MessageOutcomeV1
{
    [JsonPropertyName("status")] public string Status { get; init; } = string.Empty;
    [JsonPropertyName("result")] public JsonElement? Result { get; init; }
    [JsonPropertyName("error")] public MessageErrorV1? Error { get; init; }
}

public sealed record class MessageErrorV1
{
    [JsonPropertyName("code")] public string Code { get; init; } = string.Empty;
    [JsonPropertyName("message")] public string Message { get; init; } = string.Empty;
    [JsonPropertyName("retryable")] public bool Retryable { get; init; }
    [JsonPropertyName("details")] public JsonElement? Details { get; init; }
}
